import type { DoorayApi } from '@dooray-sdk/client';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import { registerProjectCategoryList } from './category-list';
import { registerProjectCheckName } from './check-name';
import { registerProjectCreate } from './create';
import { registerProjectEmailCreate } from './email-create';
import { registerProjectEmailView } from './email-view';
import { registerProjectHookCreate } from './hook-create';
import { registerProjectList } from './list';
import { registerProjectMemberAdd } from './member-add';
import { registerProjectMemberGroupList } from './member-group-list';
import { registerProjectMemberGroupView } from './member-group-view';
import { registerProjectMemberList } from './member-list';
import { registerProjectMemberView } from './member-view';
import { registerProjectMilestoneCreate } from './milestone-create';
import { registerProjectMilestoneDelete } from './milestone-delete';
import { registerProjectMilestoneList } from './milestone-list';
import { registerProjectMilestoneUpdate } from './milestone-update';
import { registerProjectMilestoneView } from './milestone-view';
import { registerProjectStatusCreate } from './status-create';
import { registerProjectStatusDelete } from './status-delete';
import { registerProjectStatusList } from './status-list';
import { registerProjectStatusUpdate } from './status-update';
import { registerProjectTagCreate } from './tag-create';
import { registerProjectTagGroupUpdate } from './tag-group-update';
import { registerProjectTagList } from './tag-list';
import { registerProjectTagView } from './tag-view';
import { registerProjectTemplateDelete } from './template-delete';
import { registerProjectTemplateList } from './template-list';
import { registerProjectTemplateView } from './template-view';
import { registerProjectView } from './view';

export function registerProjectTools(server: McpServer, api: DoorayApi): void {
  registerProjectList(server, api);
  registerProjectView(server, api);
  registerProjectCreate(server, api);
  registerProjectCheckName(server, api);
  registerProjectCategoryList(server, api);
  registerProjectMemberList(server, api);
  registerProjectMemberView(server, api);
  registerProjectMemberAdd(server, api);
  registerProjectMemberGroupList(server, api);
  registerProjectMemberGroupView(server, api);
  registerProjectMilestoneList(server, api);
  registerProjectMilestoneView(server, api);
  registerProjectMilestoneCreate(server, api);
  registerProjectMilestoneUpdate(server, api);
  registerProjectMilestoneDelete(server, api);
  registerProjectStatusList(server, api);
  registerProjectStatusCreate(server, api);
  registerProjectStatusUpdate(server, api);
  registerProjectStatusDelete(server, api);
  registerProjectTagList(server, api);
  registerProjectTagView(server, api);
  registerProjectTagCreate(server, api);
  registerProjectTagGroupUpdate(server, api);
  registerProjectTemplateList(server, api);
  registerProjectTemplateView(server, api);
  registerProjectTemplateDelete(server, api);
  registerProjectEmailCreate(server, api);
  registerProjectEmailView(server, api);
  registerProjectHookCreate(server, api);
}
